export default Object.freeze({
  SIGNIN: '/',
  SIGNUP: '/signup',
  BUSINESS: '/business',
  FEATURES: '/features',
  PRISING: '/prising',
  ABOUT: '/about',
  PROFILE: '/profile',
  RATING: '/rating',
  STATE: '/state',
  TASKS: '/tasks',
  HELP: '/help',
  CALENDAR: '/calendar',
  SETTINGS: '/settings',
});
