const SIGNUP_REQUEST = 'auth/SIGNUP_REQUEST';
const SIGNUP_SUCCESS = 'auth/SIGNUP_SUCCESS';
const SIGNUP_ERROR = 'auth/SIGNUP_ERROR';
const LOGIN_REQUEST = 'auth/LOGIN_REQUEST';
const LOGIN_SUCCESS = 'auth/LOGIN_SUCCESS';
const LOGIN_ERROR = 'auth/LOGIN_ERROR';
const SIGN_OUT = 'auth/SIGN_OUT';
const SET_CURRENT_USER_REQUEST = 'auth/SET_CURRENT_USER_REQUEST';
const SET_CURRENT_USER_SUCCESS = 'auth/SET_CURRENT_USER_SUCCESS';
const SET_CURRENT_USER_ERROR = 'auth/SET_CURRENT_USER_ERROR';

export default {
  SIGNUP_REQUEST,
  SIGNUP_SUCCESS,
  SIGNUP_ERROR,
  LOGIN_REQUEST,
  LOGIN_SUCCESS,
  LOGIN_ERROR,
  SIGN_OUT,
  SET_CURRENT_USER_REQUEST,
  SET_CURRENT_USER_SUCCESS,
  SET_CURRENT_USER_ERROR,
};
