const SIGNUP_REQUEST = 'auth/SIGNUP_REQUEST';
const SIGNUP_SUCCESS = 'auth/SIGNUP_SUCCESS';
const SIGNUP_ERROR = 'auth/SIGNUP_ERROR';
const LOGIN_REQUEST = 'auth/LOGIN_REQUEST';
const LOGIN_SUCCESS = 'auth/LOGIN_SUCCESS';
const LOGIN_ERROR = 'auth/LOGIN_ERROR';
const SIGN_OUT_REQUEST = 'auth/SIGN_OUT_REQUEST';
const SIGN_OUT_SUCCESS = 'auth/SIGN_OUT_SUCCESS';
const SIGN_OUT_ERROR = 'auth/SIGN_OUT_ERROR';
const SET_CURRENT_USER = 'auth/SET_CURRENT_USER';
const GET_CURRENT_USER_REQUEST = 'auth/GET_CURRENT_USER_REQUEST';
const GET_CURRENT_USER_SUCCESS = 'auth/GET_CURRENT_USER_SUCCESS';
const GET_CURRENT_USER_ERROR = 'auth/GET_CURRENT_USER_ERROR';

export default {
  SIGNUP_REQUEST,
  SIGNUP_SUCCESS,
  SIGNUP_ERROR,
  LOGIN_REQUEST,
  LOGIN_SUCCESS,
  LOGIN_ERROR,
  SIGN_OUT_REQUEST,
  SIGN_OUT_SUCCESS,
  SIGN_OUT_ERROR,
  SET_CURRENT_USER,
  GET_CURRENT_USER_REQUEST,
  GET_CURRENT_USER_SUCCESS,
  GET_CURRENT_USER_ERROR,
};
