const USERS_FETCH_REQUEST = 'users/FETCH_REQUEST';
const USERS_FETCH_SUCCESS = 'users/FETCH_SUCCESS';
const USERS_FETCH_ERROR = 'users/FETCH_ERROR';

export default {
  USERS_FETCH_REQUEST,
  USERS_FETCH_SUCCESS,
  USERS_FETCH_ERROR,
};
